### ISSUE TITLE
Alpha | User authentication

### ISSUE THREAD

**Issue by paulwsully** [paulwsully/VGina#22]

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i'm interesting in this issue if there is no currenlty working on it

**Comment by paulwsully** [comment]
> Hi, i'm interesting in this issue if there is no currenlty working on it

Hey there! Nope. I've not started it yet myself. Though I do plan to use authentication provided by Firebase when I do finally get around to implementing it.
